server:
  port: 8081
  servlet:
    context-path: /app

value:
  name: dan
  lastname: rey

user:
  email: test@email.com
  password: 1234
  age: 25

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error
